import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { format } from 'date-fns';
import { FileText, Download, Printer, ArrowRight, ShieldAlert } from 'lucide-react';
import { reportsApi } from '../services/api';
import SeverityBadge from '../components/SeverityBadge';
import Spinner from '../components/Spinner';
import EmptyState from '../components/EmptyState';

export default function Reports() {
  const navigate = useNavigate();

  const { data: reports = [], isLoading } = useQuery({
    queryKey: ['allReports'],
    queryFn: async () => {
      const res = await reportsApi.getAllReports();
      return res.data;
    }
  });

  const handleDownload = async (caseId, reportNumber, formatType = 'md') => {
    try {
      const res = await reportsApi.exportReport(caseId, formatType);
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${reportNumber}.${formatType}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      alert('Failed to download report');
    }
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="p-5 bg-[#0f1422] border border-slate-800 rounded-2xl flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <h2 className="text-base font-bold font-mono text-slate-100 uppercase tracking-wide">
              Official Incident & Forensic Investigation Reports
            </h2>
          </div>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Archival repository of completed forensic case reports with executive summaries, evidence chain, and actionable hardening recommendations.
          </p>
        </div>

        <div className="text-xs font-mono text-slate-400">
          Generated Reports: <strong className="text-cyan-400 font-bold">{reports.length}</strong>
        </div>
      </div>

      {/* Reports List */}
      {isLoading ? (
        <div className="py-16 text-center">
          <Spinner size="md" />
        </div>
      ) : reports.length === 0 ? (
        <EmptyState
          title="No incident reports generated"
          description="Compile a report from any active case in the Case Investigation Workspace."
          icon={FileText}
        />
      ) : (
        <div className="space-y-4 font-mono text-xs">
          {reports.map((rpt) => (
            <div
              key={rpt._id}
              className="p-5 bg-[#0f1422] border border-slate-800 rounded-xl hover:border-slate-700 transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-lg"
            >
              <div className="space-y-1.5 flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-cyan-400 text-sm">{rpt.reportNumber}</span>
                  <SeverityBadge severity={rpt.severity} />
                  <span className="text-slate-500 text-[11px]">
                    Case: {rpt.caseId?.caseId || 'Direct'}
                  </span>
                </div>

                <h3 className="text-sm font-bold text-slate-100">
                  {rpt.title}
                </h3>

                <p className="text-xs text-slate-400 font-sans line-clamp-2 leading-relaxed">
                  {rpt.sections?.incidentSummary || 'Forensic investigation report compiled.'}
                </p>

                <div className="text-[11px] text-slate-500 pt-1">
                  Generated by <strong>{rpt.generatedBy?.fullName || 'Analyst'}</strong> on {rpt.generatedAt ? format(new Date(rpt.generatedAt), 'yyyy-MM-dd HH:mm:ss') : 'N/A'}
                </div>
              </div>

              <div className="flex flex-wrap items-center gap-2 self-end md:self-center">
                <button
                  onClick={() => handleDownload(rpt.caseId?._id || rpt.caseId, rpt.reportNumber, 'md')}
                  className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors flex items-center gap-1.5"
                  title="Export Markdown"
                >
                  <Download className="w-3.5 h-3.5" /> Markdown
                </button>

                <button
                  onClick={() => handleDownload(rpt.caseId?._id || rpt.caseId, rpt.reportNumber, 'html')}
                  className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-cyan-300 hover:text-cyan-200 transition-colors flex items-center gap-1.5"
                  title="Export HTML Document"
                >
                  <Printer className="w-3.5 h-3.5" /> HTML
                </button>

                <button
                  onClick={() => navigate(`/cases/${rpt.caseId?._id || rpt.caseId}`)}
                  className="px-3.5 py-1.5 rounded-lg bg-cyan-500/15 border border-cyan-500/50 hover:bg-cyan-500/25 text-cyan-300 font-bold transition-colors flex items-center gap-1.5"
                >
                  View Case <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
